export const campaignVaultAbi = [
  {
    type: "function",
    name: "createCampaign",
    stateMutability: "nonpayable",
    inputs: [
      { name: "publisher", type: "address" },
      { name: "budget", type: "uint256" },
      { name: "deadline", type: "uint64" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ name: "campaignId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createCampaignWithMilestones",
    stateMutability: "nonpayable",
    inputs: [
      { name: "publisher", type: "address" },
      { name: "budget", type: "uint256" },
      { name: "deadline", type: "uint64" },
      { name: "metadataHash", type: "bytes32" },
      { name: "milestoneCount", type: "uint16" },
    ],
    outputs: [{ name: "campaignId", type: "uint256" }],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "markDelivered",
    stateMutability: "nonpayable",
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "proofHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "markMilestoneDelivered",
    stateMutability: "nonpayable",
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "proofHash", type: "bytes32" },
      { name: "milestoneIndex", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "release",
    stateMutability: "nonpayable",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "releaseMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "campaigns",
    stateMutability: "view",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [
      { name: "advertiser", type: "address" },
      { name: "publisher", type: "address" },
      { name: "budget", type: "uint256" },
      { name: "deadline", type: "uint64" },
      { name: "status", type: "uint8" },
      { name: "metadataHash", type: "bytes32" },
      { name: "proofHash", type: "bytes32" },
      { name: "milestoneCount", type: "uint16" },
      { name: "deliveredMilestones", type: "uint16" },
      { name: "releasedMilestones", type: "uint16" },
      { name: "releasedAmount", type: "uint256" },
      { name: "feePaid", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getMilestoneState",
    stateMutability: "view",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [
      { name: "milestoneCount", type: "uint16" },
      { name: "deliveredMilestones", type: "uint16" },
      { name: "releasedMilestones", type: "uint16" },
      { name: "releasedAmount", type: "uint256" },
      { name: "remainingAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "milestoneProofs",
    stateMutability: "view",
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "milestoneIndex", type: "uint16" },
    ],
    outputs: [{ name: "proofHash", type: "bytes32" }],
  },
  {
    type: "function",
    name: "MAX_MILESTONE_COUNT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "refund",
    stateMutability: "nonpayable",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "assignPublisher",
    stateMutability: "nonpayable",
    inputs: [
      { name: "campaignId", type: "uint256" },
      { name: "publisher", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "CampaignCreated",
    inputs: [
      { name: "campaignId", type: "uint256", indexed: true },
      { name: "advertiser", type: "address", indexed: true },
      { name: "publisher", type: "address", indexed: true },
      { name: "budget", type: "uint256", indexed: false },
      { name: "deadline", type: "uint64", indexed: false },
      { name: "metadataHash", type: "bytes32", indexed: false },
    ],
    anonymous: false,
  },
] as const;
